// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7R9rw12OXzES_jGnrPkrwMA7YVH71irA',
    appId: '1:808890816088:web:51d6f38e54963ba1a1dc2d',
    messagingSenderId: '808890816088',
    projectId: 'ihmproject-a1a57',
    authDomain: 'ihmproject-a1a57.firebaseapp.com',
    storageBucket: 'ihmproject-a1a57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAngxacsRgi352gHwW4Ccd5YWVfmsa1SO0',
    appId: '1:808890816088:android:5d70ac7c7038d983a1dc2d',
    messagingSenderId: '808890816088',
    projectId: 'ihmproject-a1a57',
    storageBucket: 'ihmproject-a1a57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVUxveyMu5vBS-Mx021Woge9JAA5MqNcM',
    appId: '1:808890816088:ios:845be8f0c827bf2da1dc2d',
    messagingSenderId: '808890816088',
    projectId: 'ihmproject-a1a57',
    storageBucket: 'ihmproject-a1a57.appspot.com',
    iosClientId: '808890816088-ob5em7mloem4ur0ajjgns90peoc64ohj.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeihmproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVUxveyMu5vBS-Mx021Woge9JAA5MqNcM',
    appId: '1:808890816088:ios:845be8f0c827bf2da1dc2d',
    messagingSenderId: '808890816088',
    projectId: 'ihmproject-a1a57',
    storageBucket: 'ihmproject-a1a57.appspot.com',
    iosClientId: '808890816088-ob5em7mloem4ur0ajjgns90peoc64ohj.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeihmproject',
  );
}
